import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  BarChart3, BookOpen, Building2, CalendarDays, ChevronDown, ClipboardList, Download,
  FileSpreadsheet, FileText, Home, LogOut, PackageCheck, Plus, Printer, RefreshCw,
  Search, Settings, ShoppingCart, Sparkles, Truck, Users, Warehouse, X, CheckCircle2,
  AlertTriangle, Clock3, Target, Boxes, Pencil, Save, Eye, Filter, CalendarRange
} from 'lucide-react';

type User = { id:string; email:string; full_name:string; role:string; status:string; institution_id?:string|null; must_change_password?:number };
type Bootstrap = { user:User; seasons:any[]; grades:any[]; publishers:any[]; institutions:any[] };
const MONTHS = [
  {v:'09',n:'Eylül'},{v:'10',n:'Ekim'},{v:'11',n:'Kasım'},{v:'12',n:'Aralık'},
  {v:'01',n:'Ocak'},{v:'02',n:'Şubat'},{v:'03',n:'Mart'},{v:'04',n:'Nisan'},{v:'05',n:'Mayıs'},{v:'06',n:'Haziran'}
];
const fmtMoney=(n:any)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(n||0)/100);
const fmtDate=(s?:string)=>s?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${s}T12:00:00`)):'—';
const fmtShort=(s?:string)=>s?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short'}).format(new Date(`${s}T12:00:00`)):'—';
async function api(path:string, opts:RequestInit={}):Promise<any>{
  const headers:any={'Content-Type':'application/json',...(opts.headers||{})};
  const r=await fetch(path,{...opts,headers,credentials:'same-origin'});
  const data:any=await r.json().catch(()=>({ok:false,error:'Sunucudan geçersiz yanıt'}));
  if(r.status===401 && path!='/api/auth/login' && path!='/api/auth/me'){ location.reload(); }
  if(!r.ok || data.ok===false) throw new Error(data.error||'İşlem başarısız');
  return data;
}
function useAsync<T>(factory:()=>Promise<T>, deps:any[]=[]){
  const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const run=async()=>{setLoading(true);setError('');try{setData(await factory())}catch(e:any){setError(e.message||String(e))}finally{setLoading(false)}};
  useEffect(()=>{run()},deps); return {data,loading,error,reload:run,setData};
}

export default function App(){
  const [user,setUser]=useState<User|null>(null); const [boot,setBoot]=useState<Bootstrap|null>(null); const [checking,setChecking]=useState(true);
  const load=async()=>{setChecking(true);try{const me=await api('/api/auth/me');setUser(me.user);const b=await api('/api/bootstrap');setBoot(b)}catch{setUser(null);setBoot(null)}finally{setChecking(false)}};
  useEffect(()=>{load()},[]);
  if(checking) return <Splash text="Platform hazırlanıyor…"/>;
  if(!user) return <Login onLogin={async(u)=>{setUser(u);const b=await api('/api/bootstrap');setBoot(b)}}/>;
  if(!boot) return <Splash text="Veriler yükleniyor…"/>;
  return <Shell user={user} boot={boot} refreshBoot={async()=>setBoot(await api('/api/bootstrap'))} onLogout={async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.reload()}}/>;
}

function Splash({text}:{text:string}){return <div className="splash"><div className="brand-orbit"><span>★</span></div><strong>Yıldız Deneme Platformu</strong><small>{text}</small></div>}
function Login({onLogin}:{onLogin:(u:User)=>void}){
  const [email,setEmail]=useState('admin@yildizyayin.com'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(d.user)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  return <div className="login-page"><div className="login-stars"/><div className="login-card">
    <div className="login-brand"><div className="star-logo">★</div><div><h1>Yıldız Deneme</h1><p>Takvim · Satış · Tedarik · Teslimat</p></div></div>
    <h2>Platforma giriş yapın</h2><p className="muted">Deneme sezonunu tek merkezden yönetin.</p>
    <form onSubmit={submit}><label>E-posta<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoFocus/></label><label>Şifre<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="error-box">{error}</div>}<button className="btn primary wide" disabled={busy}>{busy?'Giriş yapılıyor…':'Giriş Yap'}</button></form>
    <div className="login-foot">Yıldız Yayın Basım Dağıtım Hizmetleri</div>
  </div></div>
}

const nav=[
 {key:'dashboard',label:'Ana Sayfa',icon:Home},
 {key:'exams',label:'Denemeler',icon:BookOpen,subs:['Deneme Kataloğu','Deneme Takvimi']},
 {key:'institutions',label:'Kurumlar',icon:Building2,subs:['Kurumlar','Deneme Planları','Kurum Takvimleri']},
 {key:'sales',label:'Satış',icon:ShoppingCart,subs:['Satış Fırsatları','Sipariş Bekleyenler','Siparişler']},
 {key:'publishers',label:'Yayınevleri',icon:Warehouse,subs:['Yayınevleri','Toplu Siparişler']},
 {key:'operations',label:'Operasyon',icon:Truck,subs:['Tedarik','Gelen Ürünler','Teslimatlar']},
 {key:'reports',label:'Raporlar',icon:BarChart3},
 {key:'management',label:'Yönetim',icon:Settings,roles:['SUPER_ADMIN','ADMIN'],subs:['Kullanıcılar','Sezonlar','Ayarlar','Entegrasyonlar']},
];
function Shell({user,boot,refreshBoot,onLogout}:{user:User;boot:Bootstrap;refreshBoot:()=>Promise<void>;onLogout:()=>void}){
  const [section,setSection]=useState('dashboard'),[sub,setSub]=useState(''); const [mobile,setMobile]=useState(false);
  const visible=nav.filter(n=>!n.roles||n.roles.includes(user.role));
  const choose=(k:string,s='')=>{setSection(k);setSub(s);setMobile(false)};
  return <><div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}>
    <div className="brand"><div className="brand-icon">★</div><div><b>Yıldız Deneme</b><small>Operasyon Platformu</small></div></div>
    <nav>{visible.map(n=>{const I=n.icon;return <div key={n.key}><button className={`nav-main ${section===n.key?'active':''}`} onClick={()=>choose(n.key,n.subs?.[0]||'')}><I size={19}/><span>{n.label}</span>{n.subs&&<ChevronDown size={14}/>}</button>{section===n.key&&n.subs&&<div className="subnav">{n.subs.map(s=><button key={s} className={sub===s?'active':''} onClick={()=>setSub(s)}>{s}</button>)}</div>}</div>})}</nav>
    <div className="sidebar-foot"><div className="user-mini"><div className="avatar">{user.full_name?.[0]||'Y'}</div><div><b>{user.full_name}</b><small>{roleName(user.role)}</small></div></div><button className="icon-btn" title="Çıkış" onClick={onLogout}><LogOut size={18}/></button></div>
  </aside>
  <main className="main-area"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>☰</button><div><span className="eyebrow">2026–2027 Deneme Sezonu</span><h2>{pageTitle(section,sub)}</h2></div><div className="top-actions"><span className="status-dot">● Sistem aktif</span></div></header>
    <div className="content">
      {section==='dashboard'&&<Dashboard user={user}/>} {section==='exams'&&<Exams boot={boot} sub={sub} user={user}/>} {section==='institutions'&&<Institutions boot={boot} sub={sub} user={user} refreshBoot={refreshBoot}/>} {section==='sales'&&<Sales boot={boot} sub={sub} user={user}/>} {section==='publishers'&&<Publishers boot={boot} sub={sub} user={user} refreshBoot={refreshBoot}/>} {section==='operations'&&<Operations boot={boot} sub={sub}/>} {section==='reports'&&<Reports/>} {section==='management'&&<Management boot={boot} sub={sub} refreshBoot={refreshBoot}/>} 
    </div></main></div>{user.must_change_password? <ChangePasswordModal/> : null}</>
}
const roleName=(r:string)=>({SUPER_ADMIN:'Süper Admin',ADMIN:'Yönetici',PERSONEL:'Satış Personeli',OPERASYON:'Operasyon',KURUM:'Kurum'} as any)[r]||r;
const pageTitle=(s:string,sub:string)=>sub||({dashboard:'Genel Bakış',reports:'Ticari Raporlar'} as any)[s]||'Yıldız Deneme';


function ChangePasswordModal(){
  const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[again,setAgain]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const save=async()=>{setError('');if(next.length<10)return setError('Yeni şifre en az 10 karakter olmalı.');if(next!==again)return setError('Yeni şifreler eşleşmiyor.');setBusy(true);try{await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({current_password:current,new_password:next})});location.reload()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  return <div className="modal-back force"><div className="modal small-modal"><div className="modal-head"><div><span className="eyebrow">Güvenlik</span><h2>Geçici şifrenizi değiştirin</h2></div></div><p className="muted">İlk giriş güvenliği için yeni bir şifre belirlemeden platform kullanılamaz.</p><Field label="Mevcut geçici şifre"><input type="password" value={current} onChange={e=>setCurrent(e.target.value)} autoFocus/></Field><Field label="Yeni şifre"><input type="password" value={next} onChange={e=>setNext(e.target.value)}/></Field><Field label="Yeni şifre tekrar"><input type="password" value={again} onChange={e=>setAgain(e.target.value)}/></Field>{error&&<div className="error-box">{error}</div>}<button className="btn primary wide" disabled={busy} onClick={save}>{busy?'Kaydediliyor…':'Şifremi Değiştir'}</button></div></div>
}

function Dashboard({user}:{user:User}){
 const q=useAsync(()=>api('/api/dashboard'),[]); if(q.loading)return <Loading/>; if(q.error)return <ErrorState text={q.error} retry={q.reload}/>; const d:any=q.data||{};
 return <><div className="hero"><div><span className="pill gold"><Sparkles size={14}/> Sezon Kontrol Merkezi</span><h1>{user.role==='KURUM'?'Deneme planınız hazır.':'Deneme sezonunun tamamı tek ekranda.'}</h1><p>{user.role==='KURUM'?'Takviminizi, siparişlerinizi ve teslimatlarınızı takip edin.':'Son sipariş tarihlerini, planlanan satışları, tedariki ve teslimatı kaçırmayın.'}</p></div><div className="hero-orbit">★</div></div>
 <div className="kpi-grid"><Kpi icon={ShoppingCart} label="Toplam Sipariş" value={d.orders?.total||0} sub={`${d.orders?.quantity||0} adet`}/><Kpi icon={BarChart3} label="Ciro" value={fmtMoney(d.orders?.revenue)} sub={`${d.orders?.pending||0} aktif sipariş`}/><Kpi icon={CalendarDays} label="Yaklaşan Deneme" value={d.upcoming||0} sub="Önümüzdeki 30 gün"/><Kpi icon={Target} label="Satış Fırsatı" value={d.opportunities||0} sub={`${d.plan_pending||0} plan sipariş bekliyor`}/><Kpi icon={Truck} label="Teslimat Bekliyor" value={d.pending_deliveries||0} sub="Operasyon takibi"/></div>
 <div className="grid-2"><Panel title="Yaklaşan son sipariş tarihleri" icon={Clock3}>{d.deadlines?.length?d.deadlines.map((x:any)=><div className="deadline" key={x.id}><div><b>{x.name}</b><small>{x.publisher} · {x.grade}</small></div><span>{fmtShort(x.last_order_date)}</span></div>):<Empty text="Yaklaşan kritik tarih yok."/>}</Panel><Panel title="Bugün neye odaklanmalı?" icon={Sparkles}><ActionRow tone="warn" title={`${d.plan_pending||0} plan sipariş bekliyor`} text="Planlanmış ama henüz siparişe dönüşmemiş kayıtları satış fırsatlarında takip edin."/><ActionRow tone="info" title={`${d.pending_deliveries||0} teslimat tamamlanmadı`} text="Uygulama tarihinden önce teslimatları kapatın."/></Panel></div></>
}
function Kpi({icon:I,label,value,sub}:{icon:any;label:string;value:any;sub:string}){return <div className="kpi"><div className="kpi-icon"><I size={20}/></div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Panel({title,icon:I,children}:{title:string;icon:any;children:any}){return <section className="panel"><div className="panel-head"><div><I size={18}/><h3>{title}</h3></div></div>{children}</section>}
function ActionRow({tone,title,text}:{tone:string;title:string;text:string}){return <div className={`action-row ${tone}`}><AlertTriangle size={18}/><div><b>{title}</b><small>{text}</small></div></div>}

function Exams({boot,sub,user}:{boot:Bootstrap;sub:string;user:User}){return sub==='Deneme Takvimi'?<MasterCalendar boot={boot}/>:<ExamCatalog boot={boot} canEdit={['SUPER_ADMIN','ADMIN'].includes(user.role)}/>}
function ExamCatalog({boot,canEdit}:{boot:Bootstrap;canEdit:boolean}){
 const [season,setSeason]=useState(boot.seasons.find(s=>s.is_active)?.id||boot.seasons[0]?.id||''),[grade,setGrade]=useState(''),[q,setQ]=useState(''),[modal,setModal]=useState(false); const list=useAsync(()=>api(`/api/exams?season_id=${season}${grade?`&grade_level_id=${grade}`:''}${q?`&q=${encodeURIComponent(q)}`:''}`),[season,grade,q]);
 return <><Toolbar><select value={season} onChange={e=>setSeason(e.target.value)}>{boot.seasons.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Tüm sınıflar</option>{boot.grades.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><SearchBox value={q} set={setQ}/>{canEdit&&<button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Deneme Ekle</button>}</Toolbar>{list.loading?<Loading/>:<DataTable cols={['Tarih','Sınıf','Yayınevi','Deneme','Kod','Son Sipariş','Satış Fiyatı','Durum']} rows={(list.data as any)?.items?.map((x:any)=>[fmtShort(x.application_start_date),x.grade_name,x.publisher_short||x.publisher_name,x.name,x.code,fmtDate(x.last_order_date),fmtMoney(x.default_sale_price),<Badge key="b" text={x.is_active?'Aktif':'Pasif'} tone={x.is_active?'good':'muted'}/>])||[]}/>} {modal&&<ExamModal boot={boot} season={season} close={()=>setModal(false)} saved={()=>{setModal(false);list.reload()}}/>}</>
}
function ExamModal({boot,season,close,saved}:{boot:Bootstrap;season:string;close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({season_id:season,publisher_id:boot.publishers[0]?.id,grade_level_id:boot.grades[0]?.id,minimum_order:1});const [err,setErr]=useState('');const submit=async()=>{try{await api('/api/exams',{method:'POST',body:JSON.stringify({...b,list_price:Math.round(Number(b.list_price||0)*100),purchase_price:Math.round(Number(b.purchase_price||0)*100),default_sale_price:Math.round(Number(b.default_sale_price||0)*100)})});saved()}catch(e:any){setErr(e.message)}};return <Modal title="Yeni deneme" close={close}><FormGrid><Field label="Yayınevi"><select value={b.publisher_id} onChange={e=>setB({...b,publisher_id:e.target.value})}>{boot.publishers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Sınıf düzeyi"><select value={b.grade_level_id} onChange={e=>setB({...b,grade_level_id:e.target.value})}>{boot.grades.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></Field><Field label="Deneme adı"><input value={b.name||''} onChange={e=>setB({...b,name:e.target.value})}/></Field><Field label="Kod"><input value={b.code||''} onChange={e=>setB({...b,code:e.target.value})}/></Field><Field label="Son sipariş"><input type="date" value={b.last_order_date||''} onChange={e=>setB({...b,last_order_date:e.target.value})}/></Field><Field label="Tahmini sevk"><input type="date" value={b.estimated_ship_date||''} onChange={e=>setB({...b,estimated_ship_date:e.target.value})}/></Field><Field label="Uygulama başlangıcı"><input type="date" value={b.application_start_date||''} onChange={e=>setB({...b,application_start_date:e.target.value})}/></Field><Field label="Uygulama bitişi"><input type="date" value={b.application_end_date||''} onChange={e=>setB({...b,application_end_date:e.target.value})}/></Field><Field label="Liste fiyatı (TL)"><input type="number" value={b.list_price||''} onChange={e=>setB({...b,list_price:e.target.value})}/></Field><Field label="Alış fiyatı (TL)"><input type="number" value={b.purchase_price||''} onChange={e=>setB({...b,purchase_price:e.target.value})}/></Field><Field label="Satış fiyatı (TL)"><input type="number" value={b.default_sale_price||''} onChange={e=>setB({...b,default_sale_price:e.target.value})}/></Field><Field label="Minimum sipariş"><input type="number" value={b.minimum_order||1} onChange={e=>setB({...b,minimum_order:e.target.value})}/></Field></FormGrid>{err&&<div className="error-box">{err}</div>}<ModalActions close={close} save={submit}/></Modal>}
function MasterCalendar({boot}:{boot:Bootstrap}){const [season,setSeason]=useState(boot.seasons.find(s=>s.is_active)?.id||boot.seasons[0]?.id||''),[grade,setGrade]=useState('');const q=useAsync(()=>api(`/api/exams?season_id=${season}${grade?`&grade_level_id=${grade}`:''}`),[season,grade]);const grouped=useMemo(()=>groupByMonth((q.data as any)?.items||[],'application_start_date'),[q.data]);return <><Toolbar><select value={season} onChange={e=>setSeason(e.target.value)}>{boot.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Tüm sınıflar</option>{boot.grades.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Toolbar><div className="season-board">{MONTHS.map(m=><div className="month-card" key={m.v}><h3>{m.n}</h3>{(grouped[m.v]||[]).map((x:any)=><div className="exam-event" key={x.id}><span>{fmtShort(x.application_start_date)}</span><b>{x.grade_name} · {x.publisher_short}</b><small>{x.name}</small><em>Son sipariş {fmtShort(x.last_order_date)}</em></div>)}{!(grouped[m.v]||[]).length&&<small className="muted">Planlı deneme yok</small>}</div>)}</div></>}
function groupByMonth(items:any[],key:string){return items.reduce((a:any,x:any)=>{const d=x[key];if(d){const m=d.slice(5,7);(a[m] ||= []).push(x)}return a},{})}

function Institutions({boot,sub,user,refreshBoot}:{boot:Bootstrap;sub:string;user:User;refreshBoot:()=>Promise<void>}){if(sub==='Deneme Planları')return <PlanBuilder boot={boot} user={user}/>;if(sub==='Kurum Takvimleri')return <InstitutionCalendar boot={boot} user={user}/>;return <InstitutionList boot={boot} canEdit={['SUPER_ADMIN','ADMIN'].includes(user.role)} refreshBoot={refreshBoot}/>}
function InstitutionList({boot,canEdit,refreshBoot}:{boot:Bootstrap;canEdit:boolean;refreshBoot:()=>Promise<void>}){const [q,setQ]=useState(''),[modal,setModal]=useState(false);const list=useAsync(()=>api(`/api/institutions${q?`?q=${encodeURIComponent(q)}`:''}`),[q]);return <><Toolbar><SearchBox value={q} set={setQ}/>{canEdit&&<button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Kurum Ekle</button>}</Toolbar>{list.loading?<Loading/>:<DataTable cols={['Kurum','Kod','Tür','İlçe','Yetkili','Personel','Kapasite','Durum']} rows={(list.data as any)?.items?.map((x:any)=>[x.name,x.code,x.type||'—',x.district||'—',x.contact_person||'—',x.staff_name||'Atanmadı',x.estimated_capacity||0,<Badge key="b" text={x.is_active?'Aktif':'Pasif'} tone={x.is_active?'good':'muted'}/>])||[]}/>} {modal&&<InstitutionModal boot={boot} close={()=>setModal(false)} saved={async()=>{setModal(false);await refreshBoot();list.reload()}}/>}</>}
function InstitutionModal({boot,close,saved}:{boot:Bootstrap;close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({province:'İstanbul',is_private:true,grade_level_ids:[]});const submit=async()=>{await api('/api/institutions',{method:'POST',body:JSON.stringify(b)});saved()};const toggle=(id:string)=>setB({...b,grade_level_ids:b.grade_level_ids.includes(id)?b.grade_level_ids.filter((x:string)=>x!==id):[...b.grade_level_ids,id]});return <Modal title="Yeni kurum" close={close}><FormGrid><Field label="Kurum adı"><input value={b.name||''} onChange={e=>setB({...b,name:e.target.value})}/></Field><Field label="Kurum kodu"><input value={b.code||''} onChange={e=>setB({...b,code:e.target.value})}/></Field><Field label="Kurum türü"><input placeholder="Kolej, Anadolu Lisesi, Kurs…" value={b.type||''} onChange={e=>setB({...b,type:e.target.value})}/></Field><Field label="İlçe"><input value={b.district||''} onChange={e=>setB({...b,district:e.target.value})}/></Field><Field label="Yetkili"><input value={b.contact_person||''} onChange={e=>setB({...b,contact_person:e.target.value})}/></Field><Field label="Telefon"><input value={b.phone||''} onChange={e=>setB({...b,phone:e.target.value})}/></Field><Field label="Tahmini kapasite"><input type="number" value={b.estimated_capacity||''} onChange={e=>setB({...b,estimated_capacity:e.target.value})}/></Field></FormGrid><Field label="Aktif sınıf düzeyleri"><div className="chip-wrap">{boot.grades.map(g=><button type="button" key={g.id} className={`chip ${b.grade_level_ids.includes(g.id)?'active':''}`} onClick={()=>toggle(g.id)}>{g.name}</button>)}</div></Field><ModalActions close={close} save={submit}/></Modal>}

function PlanBuilder({boot,user}:{boot:Bootstrap;user:User}){const activeSeason=boot.seasons.find(s=>s.is_active)?.id||boot.seasons[0]?.id||'';const [inst,setInst]=useState(user.role==='KURUM'?user.institution_id||'':boot.institutions[0]?.id||''),[season,setSeason]=useState(activeSeason),[grade,setGrade]=useState(boot.grades[0]?.id||''),[selected,setSelected]=useState<string[]>([]),[msg,setMsg]=useState('');const exams=useAsync(()=>api(`/api/exams?season_id=${season}&grade_level_id=${grade}`),[season,grade]);const plans=useAsync(()=>inst?api(`/api/plans?institution_id=${inst}&season_id=${season}`):Promise.resolve({items:[]}),[inst,season]);const existing=new Set(((plans.data as any)?.items||[]).map((x:any)=>x.exam_id));const choose=(x:string)=>setSelected(s=>s.includes(x)?s.filter(i=>i!==x):[...s,x]);const save=async()=>{if(!selected.length)return;const d=await api('/api/plans',{method:'POST',body:JSON.stringify({institution_id:inst,season_id:season,exam_ids:selected})});setMsg(`${d.added} deneme takvime eklendi.`);setSelected([]);plans.reload()};return <><div className="step-header"><div><span>1</span><b>Kurum ve sezon</b></div><div><span>2</span><b>Sınıf düzeyi</b></div><div><span>3</span><b>Denemeleri seç</b></div><div><span>4</span><b>Takvimi oluştur</b></div></div><Toolbar>{user.role!=='KURUM'&&<select value={inst} onChange={e=>setInst(e.target.value)}>{boot.institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>}<select value={season} onChange={e=>setSeason(e.target.value)}>{boot.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Toolbar><div className="grade-tabs">{boot.grades.map(g=><button key={g.id} className={grade===g.id?'active':''} onClick={()=>setGrade(g.id)}>{g.name}</button>)}</div><div className="select-grid">{((exams.data as any)?.items||[]).map((x:any)=>{const has=existing.has(x.id);return <button key={x.id} disabled={has} className={`select-exam ${selected.includes(x.id)?'selected':''} ${has?'existing':''}`} onClick={()=>choose(x.id)}><span className="select-check">{has?'✓':selected.includes(x.id)?'✓':''}</span><div><b>{x.publisher_short} · {x.name}</b><small>{fmtDate(x.application_start_date)} – {fmtDate(x.application_end_date)}</small><em>Son sipariş: {fmtDate(x.last_order_date)}</em></div></button>})}</div>{msg&&<div className="success-box"><CheckCircle2 size={18}/>{msg}</div>}<div className="sticky-action"><span>{selected.length} deneme seçildi</span><button className="btn primary" disabled={!selected.length} onClick={save}><CalendarDays size={16}/> Takvimimi Oluştur</button></div></>}

function InstitutionCalendar({boot,user}:{boot:Bootstrap;user:User}){const activeSeason=boot.seasons.find(s=>s.is_active)?.id||boot.seasons[0]?.id||'';const [inst,setInst]=useState(user.role==='KURUM'?user.institution_id||'':boot.institutions[0]?.id||''),[season,setSeason]=useState(activeSeason),[month,setMonth]=useState(''),[grades,setGrades]=useState<string[]>(boot.grades.map(g=>g.id)),[mode,setMode]=useState<'calendar'|'program'>('calendar');const printRef=useRef<HTMLDivElement>(null);const query=`/api/plans?institution_id=${inst}&season_id=${season}${month?`&month=${month}`:''}`;const plans=useAsync(()=>inst?api(query):Promise.resolve({items:[]}),[inst,season,month]);const items=((plans.data as any)?.items||[]).filter((x:any)=>grades.includes(x.grade_level_id));const toggleGrade=(g:string)=>setGrades(s=>s.includes(g)?s.filter(x=>x!==g):[...s,g]);const setDate=async(x:any,date:string)=>{await api(`/api/plans/${x.id}`,{method:'PATCH',body:JSON.stringify({institution_application_date:date})});plans.reload()};
 const exportPdf=async()=>{if(!printRef.current)return;const mod=await import('html2pdf.js');const html2pdf=(mod as any).default||mod;await html2pdf().set({margin:8,filename:`deneme-takvimi-${month||'sezon'}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:month?'landscape':'portrait'}}).from(printRef.current).save()};
 const exportXlsx=async()=>{const XLSX=await import('xlsx');const rows=items.map((x:any)=>({Tarih:x.institution_application_date||x.application_start_date,Ay:monthName((x.institution_application_date||x.application_start_date)?.slice(5,7)),Sınıf:x.grade_name,Yayınevi:x.publisher_name,Deneme:x.exam_name,Kod:x.exam_code,'Uygulama Başlangıcı':x.application_start_date,'Uygulama Bitişi':x.application_end_date,'Kurum Uygulama Tarihi':x.institution_application_date||'', 'Sipariş Durumu':x.order_status||x.status,Adet:x.order_quantity||x.planned_quantity||''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Genel Takvim');for(const g of boot.grades){const rr=rows.filter((r:any)=>r['Sınıf']===g.name);if(rr.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rr),g.name.slice(0,31));}XLSX.writeFile(wb,`Yildiz-Deneme-Takvimi-${month||'Sezon'}.xlsx`)};
 return <><Toolbar>{user.role!=='KURUM'&&<select value={inst} onChange={e=>setInst(e.target.value)}>{boot.institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>}<select value={season} onChange={e=>setSeason(e.target.value)}>{boot.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Tüm sezon</option>{MONTHS.map(m=><option value={m.v} key={m.v}>{m.n}</option>)}</select><div className="segmented"><button className={mode==='calendar'?'active':''} onClick={()=>setMode('calendar')}><CalendarDays size={15}/></button><button className={mode==='program'?'active':''} onClick={()=>setMode('program')}><ClipboardList size={15}/></button></div><div className="spacer"/><button className="btn" onClick={exportPdf}><FileText size={16}/> PDF</button><button className="btn" onClick={exportXlsx}><FileSpreadsheet size={16}/> Excel</button><button className="btn" onClick={()=>window.print()}><Printer size={16}/> Yazdır</button></Toolbar><div className="grade-tabs multi"><button className={grades.length===boot.grades.length?'active':''} onClick={()=>setGrades(boot.grades.map(g=>g.id))}>Tümü</button>{boot.grades.map(g=><button key={g.id} className={grades.includes(g.id)?'active':''} onClick={()=>toggleGrade(g.id)}>{g.name}</button>)}</div><div ref={printRef} id="calendar-print" className="print-calendar"><div className="print-head"><div className="print-star">★</div><div><b>YILDIZ YAYIN BASIM DAĞITIM HİZMETLERİ</b><h1>{boot.institutions.find(i=>i.id===inst)?.name||'Kurum Deneme Takvimi'}</h1><p>{boot.seasons.find(s=>s.id===season)?.name} · {month?monthName(month):'Sezon Geneli'} Deneme Takvimi</p></div></div>{mode==='program'?<ProgramView items={items} setDate={setDate}/>:<CalendarView items={items} month={month} setDate={setDate}/>}<div className="print-footer">Oluşturma: {new Date().toLocaleDateString('tr-TR')} · Yıldız Deneme Platformu</div></div></>}
function monthName(v?:string){return MONTHS.find(m=>m.v===v)?.n||''}
function CalendarView({items,month,setDate}:{items:any[];month:string;setDate:(x:any,d:string)=>void}){if(month){const byGrade=items.reduce((a:any,x:any)=>{(a[x.grade_name] ||= []).push(x);return a},{});return <div className="monthly-general">{Object.entries(byGrade).map(([g,arr]:any)=><section key={g}><h2>{g}</h2><div className="calendar-event-grid">{arr.map((x:any)=><CalendarEvent x={x} key={x.id} setDate={setDate}/>)}</div></section>)}</div>}const grouped=groupByMonth(items.map(x=>({...x,_date:x.institution_application_date||x.application_start_date})),'_date');return <div className="season-board print-season">{MONTHS.map(m=><div className="month-card" key={m.v}><h3>{m.n}</h3>{(grouped[m.v]||[]).map((x:any)=><CalendarEvent x={x} key={x.id} setDate={setDate} compact/>)}{!(grouped[m.v]||[]).length&&<small className="muted">—</small>}</div>)}</div>}
function CalendarEvent({x,setDate,compact}:{x:any;setDate:(x:any,d:string)=>void;compact?:boolean}){return <div className={`calendar-event grade-${x.grade_code}`}><div className="event-date"><b>{fmtShort(x.institution_application_date||x.application_start_date)}</b><span>{x.grade_name}</span></div><div className="event-main"><b>{x.publisher_short} · {x.exam_name}</b><small>{x.institution_application_date?`Kurum günü · Resmî aralık ${fmtShort(x.application_start_date)}–${fmtShort(x.application_end_date)}`:`Resmî aralık ${fmtShort(x.application_start_date)}–${fmtShort(x.application_end_date)}`}</small>{!compact&&<label className="date-edit no-print">Kurum günü <input type="date" value={x.institution_application_date||''} onChange={e=>setDate(x,e.target.value)}/></label>}</div><Badge text={x.order_status||statusLabel(x.status)} tone={x.order_id?'good':'warn'}/></div>}
function ProgramView({items,setDate}:{items:any[];setDate:(x:any,d:string)=>void}){return <DataTable cols={['Tarih','Sınıf','Yayınevi','Deneme','Resmî Aralık','Sipariş','Kurum Günü']} rows={items.map(x=>[fmtDate(x.institution_application_date||x.application_start_date),x.grade_name,x.publisher_name,x.exam_name,`${fmtShort(x.application_start_date)}–${fmtShort(x.application_end_date)}`,x.order_status||statusLabel(x.status),<input key="d" className="date-inline no-print" type="date" value={x.institution_application_date||''} onChange={e=>setDate(x,e.target.value)}/>])}/>} 
const statusLabel=(s:string)=>({PLANLANDI:'Planlandı',SIPARIS_BEKLIYOR:'Sipariş Bekliyor',SIPARIS_VERILDI:'Sipariş Verildi',ONAYLANDI:'Onaylandı',TEDARIK:'Tedarik',TESLIM_EDILDI:'Teslim Edildi'} as any)[s]||s;

function Sales({boot,sub,user}:{boot:Bootstrap;sub:string;user:User}){if(sub==='Siparişler')return <Orders boot={boot} user={user}/>;return <Opportunities onlyPending={sub==='Sipariş Bekleyenler'}/>}
function Opportunities({onlyPending}:{onlyPending:boolean}){const q=useAsync(()=>api('/api/opportunities'),[]);const update=async(x:any,status:string,loss_reason?:string)=>{await api(`/api/opportunities/${x.id}`,{method:'PATCH',body:JSON.stringify({status,loss_reason})});q.reload()};const items=((q.data as any)?.items||[]).filter((x:any)=>!onlyPending||['ARANACAK','GORUSULDU','TEKLIF_VERILDI','KARAR_BEKLENIYOR'].includes(x.status));return <><Toolbar><button className="btn" onClick={async()=>{await api('/api/opportunities/generate',{method:'POST'});q.reload()}}><RefreshCw size={16}/> Fırsatları Güncelle</button></Toolbar><div className="opportunity-list">{items.map((x:any)=><div className="opp-card" key={x.id}><div className={`priority ${x.priority.toLowerCase()}`}>{x.priority}</div><div className="opp-main"><b>{x.institution_name}</b><span>{x.grade_name} · {x.publisher_name} · {x.exam_name}</span><small>{x.notes||'Satış takibi'} · Son sipariş {fmtDate(x.last_order_date)}</small></div><select value={x.status} onChange={e=>update(x,e.target.value)}><option>ARANACAK</option><option>GORUSULDU</option><option>TEKLIF_VERILDI</option><option>KARAR_BEKLENIYOR</option><option>SIPARIS_VERDI</option><option>ILGILENMIYOR</option><option>BASKA_YAYINEVI_ALDI</option><option>KATILMAYACAK</option><option>ULASILAMADI</option></select></div>)}</div>{!items.length&&<Empty text="Bu filtrede satış fırsatı yok."/>}</>}
function Orders({boot,user}:{boot:Bootstrap;user:User}){const q=useAsync(()=>api('/api/orders'),[]),[modal,setModal]=useState(false);return <><Toolbar><div className="spacer"/><button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Sipariş Gir</button></Toolbar><DataTable cols={['Tarih','Kurum','Sınıf','Yayınevi','Deneme','Adet','Birim','Toplam','Durum']} rows={((q.data as any)?.items||[]).map((x:any)=>[new Date(x.created_at).toLocaleDateString('tr-TR'),x.institution_name,x.grade_name,x.publisher_name,x.exam_name,x.quantity,fmtMoney(x.unit_price),fmtMoney(x.total_price),<Badge key="b" text={x.status} tone={x.status==='TESLIM_EDILDI'?'good':'info'}/>])}/>{modal&&<OrderModal boot={boot} user={user} close={()=>setModal(false)} saved={()=>{setModal(false);q.reload()}}/>}</>}
function OrderModal({boot,user,close,saved}:{boot:Bootstrap;user:User;close:()=>void;saved:()=>void}){const [inst,setInst]=useState(user.role==='KURUM'?user.institution_id||'':boot.institutions[0]?.id||''),[exam,setExam]=useState(''),[qty,setQty]=useState(''),[price,setPrice]=useState('');const exams=useAsync(()=>api(`/api/exams?season_id=${boot.seasons.find(s=>s.is_active)?.id||''}`),[]);const save=async()=>{await api('/api/orders',{method:'POST',body:JSON.stringify({institution_id:inst,exam_id:exam,quantity:Number(qty),unit_price:price?Math.round(Number(price)*100):undefined})});saved()};return <Modal title="Sipariş oluştur" close={close}><FormGrid>{user.role!=='KURUM'&&<Field label="Kurum"><select value={inst} onChange={e=>setInst(e.target.value)}>{boot.institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field>}<Field label="Deneme"><select value={exam} onChange={e=>setExam(e.target.value)}><option value="">Seçiniz</option>{((exams.data as any)?.items||[]).map((x:any)=><option key={x.id} value={x.id}>{x.grade_name} · {x.publisher_short} · {x.name}</option>)}</select></Field><Field label="Adet"><input type="number" value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Birim fiyat (TL, boşsa varsayılan)"><input type="number" value={price} onChange={e=>setPrice(e.target.value)}/></Field></FormGrid><ModalActions close={close} save={save}/></Modal>}

function Publishers({boot,sub,user,refreshBoot}:{boot:Bootstrap;sub:string;user:User;refreshBoot:()=>Promise<void>}){return sub==='Toplu Siparişler'?<PublisherOrders user={user}/>:<PublisherList boot={boot} canEdit={['SUPER_ADMIN','ADMIN'].includes(user.role)} refreshBoot={refreshBoot}/>}
function PublisherList({boot,canEdit,refreshBoot}:{boot:Bootstrap;canEdit:boolean;refreshBoot:()=>Promise<void>}){const q=useAsync(()=>api('/api/publishers'),[]),[modal,setModal]=useState(false);return <><div className="card-grid">{((q.data as any)?.items||boot.publishers).map((x:any)=><div className="publisher-card" key={x.id}><div className="publisher-mark">{x.short_name?.slice(0,3).toUpperCase()}</div><div><h3>{x.name}</h3><p>{x.sales_representative||x.contact_person||'Yetkili tanımlanmadı'}</p><small>{x.phone||'—'} · Min. {x.minimum_order||1} adet</small></div></div>)}</div>{canEdit&&<button className="fab" onClick={()=>setModal(true)}><Plus/></button>}{modal&&<SimplePublisherModal close={()=>setModal(false)} saved={async()=>{setModal(false);await refreshBoot();q.reload()}}/>}</>}
function SimplePublisherModal({close,saved}:{close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({minimum_order:1,delivery_days:14});return <Modal title="Yayınevi ekle" close={close}><FormGrid><Field label="Yayınevi"><input value={b.name||''} onChange={e=>setB({...b,name:e.target.value})}/></Field><Field label="Kısa ad"><input value={b.short_name||''} onChange={e=>setB({...b,short_name:e.target.value})}/></Field><Field label="Satış temsilcisi"><input value={b.sales_representative||''} onChange={e=>setB({...b,sales_representative:e.target.value})}/></Field><Field label="Telefon"><input value={b.phone||''} onChange={e=>setB({...b,phone:e.target.value})}/></Field></FormGrid><ModalActions close={close} save={async()=>{await api('/api/publishers',{method:'POST',body:JSON.stringify(b)});saved()}}/></Modal>}
function PublisherOrders({user}:{user:User}){const po=useAsync(()=>api('/api/publisher-orders'),[]),orders=useAsync(()=>api('/api/orders'),[]),[selected,setSelected]=useState<string[]>([]);if(!['SUPER_ADMIN','ADMIN','OPERASYON'].includes(user.role))return <Empty text="Bu bölüm için yetkiniz yok."/>;const pending=((orders.data as any)?.items||[]).filter((x:any)=>['ONAYLANDI','YAYINEVINE_GECILECEK','SIPARIS_ALINDI'].includes(x.status));const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const create=async()=>{await api('/api/publisher-orders',{method:'POST',body:JSON.stringify({order_ids:selected})});setSelected([]);po.reload();orders.reload()};return <><Panel title="Yayınevine geçirilecek kurum siparişleri" icon={Boxes}><div className="check-list">{pending.map((x:any)=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/><span><b>{x.exam_name}</b><small>{x.institution_name} · {x.quantity} adet</small></span></label>)}</div>{selected.length>0&&<button className="btn primary" onClick={create}>Seçilenleri Toplu Siparişe Dönüştür ({selected.length})</button>}</Panel><h3 className="section-title">Toplu yayınevi siparişleri</h3><DataTable cols={['Yayınevi','Deneme','Sınıf','Toplam','Gelen','Eksik','Durum']} rows={((po.data as any)?.items||[]).map((x:any)=>[x.publisher_name,x.exam_name,x.grade_name,x.total_quantity,x.received_quantity||0,x.missing_quantity||0,<Badge key="b" text={x.status} tone={x.missing_quantity?'warn':x.status==='TAM_GELDI'?'good':'info'}/>])}/></>}

function Operations({boot,sub}:{boot:Bootstrap;sub:string}){if(sub==='Teslimatlar')return <Deliveries boot={boot}/>;return <Procurement showReceipts={sub==='Gelen Ürünler'}/>}
function Procurement({showReceipts}:{showReceipts:boolean}){const q=useAsync(()=>api('/api/publisher-orders'),[]),[receipt,setReceipt]=useState<any|null>(null);return <><DataTable cols={['Yayınevi','Deneme','Sipariş','Gelen','Eksik','Kargo','Takip','Durum','']} rows={((q.data as any)?.items||[]).map((x:any)=>[x.publisher_name,x.exam_name,x.total_quantity,x.received_quantity||0,x.missing_quantity||0,x.courier||'—',x.tracking_number||'—',<Badge key="b" text={x.status} tone={x.status==='TAM_GELDI'?'good':x.status==='KISMI_GELDI'?'warn':'info'}/>,<button key="a" className="btn tiny" onClick={()=>setReceipt(x)}>{showReceipts?'Gelen Ürün':'Ürün Kabul'}</button>])}/>{receipt&&<ReceiptModal x={receipt} close={()=>setReceipt(null)} saved={()=>{setReceipt(null);q.reload()}}/>}</>}
function ReceiptModal({x,close,saved}:{x:any;close:()=>void;saved:()=>void}){const [qty,setQty]=useState(''),[notes,setNotes]=useState('');return <Modal title={`${x.exam_name} · Ürün kabul`} close={close}><div className="summary-box"><b>Sipariş: {x.total_quantity} adet</b><span>Şimdiye kadar gelen: {x.received_quantity||0}</span><span>Eksik: {x.missing_quantity??x.total_quantity}</span></div><Field label="Bu sevkiyatta gelen adet"><input autoFocus type="number" value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="Not"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><ModalActions close={close} save={async()=>{await api('/api/goods-receipts',{method:'POST',body:JSON.stringify({publisher_order_id:x.id,received_quantity:Number(qty),notes})});saved()}}/></Modal>}
function Deliveries({boot}:{boot:Bootstrap}){const q=useAsync(()=>api('/api/deliveries'),[]),orders=useAsync(()=>api('/api/orders'),[]),[modal,setModal]=useState(false);const setStatus=async(x:any,status:string)=>{await api(`/api/deliveries/${x.id}`,{method:'PATCH',body:JSON.stringify({status,delivery_date:status==='TESLIM_EDILDI'?new Date().toISOString().slice(0,10):undefined})});q.reload()};return <><Toolbar><div className="spacer"/><button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Teslimat Oluştur</button></Toolbar><DataTable cols={['Kurum','Sınıf','Deneme','Adet','Yöntem','Kargo','Takip','Durum']} rows={((q.data as any)?.items||[]).map((x:any)=>[x.institution_name,x.grade_name,x.exam_name,x.quantity,x.delivery_method||'—',x.carrier||'—',x.tracking_number||'—',<select key="s" value={x.status} onChange={e=>setStatus(x,e.target.value)}><option>HAZIRLANIYOR</option><option>HAZIR</option><option>SEVK_EDILDI</option><option>PERSONEL_TESLIM</option><option>KARGO</option><option>KURUMDAN_TESLIM</option><option>TESLIM_EDILDI</option></select>])}/>{modal&&<DeliveryModal orders={(orders.data as any)?.items||[]} close={()=>setModal(false)} saved={()=>{setModal(false);q.reload()}}/>}</>}
function DeliveryModal({orders,close,saved}:{orders:any[];close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({delivery_method:'KARGO',status:'HAZIRLANIYOR'});return <Modal title="Teslimat oluştur" close={close}><FormGrid><Field label="Sipariş"><select value={b.order_id||''} onChange={e=>{const o=orders.find(x=>x.id===e.target.value);setB({...b,order_id:e.target.value,quantity:o?.quantity||''})}}><option value="">Seçiniz</option>{orders.filter(x=>x.status!=='IPTAL').map(x=><option key={x.id} value={x.id}>{x.institution_name} · {x.exam_name} · {x.quantity}</option>)}</select></Field><Field label="Adet"><input type="number" value={b.quantity||''} onChange={e=>setB({...b,quantity:e.target.value})}/></Field><Field label="Teslim yöntemi"><select value={b.delivery_method} onChange={e=>setB({...b,delivery_method:e.target.value})}><option>KARGO</option><option>PERSONEL_TESLIM</option><option>KURUMDAN_TESLIM</option></select></Field><Field label="Kargo / taşıyıcı"><input value={b.carrier||''} onChange={e=>setB({...b,carrier:e.target.value})}/></Field><Field label="Takip no"><input value={b.tracking_number||''} onChange={e=>setB({...b,tracking_number:e.target.value})}/></Field></FormGrid><ModalActions close={close} save={async()=>{await api('/api/deliveries',{method:'POST',body:JSON.stringify({...b,quantity:Number(b.quantity)})});saved()}}/></Modal>}

function Reports(){const q=useAsync(()=>api('/api/reports/summary'),[]);if(q.loading)return <Loading/>;const d:any=q.data||{};return <><div className="kpi-grid"><Kpi icon={CalendarRange} label="Planlanan" value={d.planned?.total||0} sub="Kurum sezon planları"/><Kpi icon={CheckCircle2} label="Siparişe Dönüşen" value={d.planned?.converted||0} sub={`${d.planned?.total?Math.round((d.planned.converted/d.planned.total)*100):0}% dönüşüm`}/></div><div className="grid-2"><Panel title="Yayınevi satışları" icon={BookOpen}><MiniReport rows={d.by_publisher||[]}/></Panel><Panel title="Sınıf düzeyi satışları" icon={Users}><MiniReport rows={d.by_grade||[]}/></Panel></div><Panel title="Kaçan satış nedenleri" icon={AlertTriangle}><DataTable cols={['Neden','Adet']} rows={(d.losses||[]).map((x:any)=>[x.label,x.count])}/></Panel></>}
function MiniReport({rows}:{rows:any[]}){const max=Math.max(...rows.map(r=>Number(r.revenue||0)),1);return <div className="mini-report">{rows.map((r:any)=><div key={r.label}><div className="mini-label"><b>{r.label}</b><span>{r.quantity||0} adet · {fmtMoney(r.revenue)}</span></div><div className="bar"><i style={{width:`${Math.max(3,Number(r.revenue||0)/max*100)}%`}}/></div></div>)}{!rows.length&&<Empty text="Henüz satış verisi yok."/>}</div>}

function Management({boot,sub,refreshBoot}:{boot:Bootstrap;sub:string;refreshBoot:()=>Promise<void>}){if(sub==='Sezonlar')return <Seasons boot={boot} refreshBoot={refreshBoot}/>;if(sub==='Kullanıcılar')return <UsersAdmin boot={boot}/>;if(sub==='Entegrasyonlar')return <Integration/>;return <Panel title="Sistem ayarları" icon={Settings}><p className="muted">Deneme Platformu kapsamı kilitlidir: takvim, kurum planlama, satış, sipariş, tedarik, teslimat ve ticari raporlama.</p></Panel>}
function UsersAdmin({boot}:{boot:Bootstrap}){const q=useAsync(()=>api('/api/users'),[]),[modal,setModal]=useState(false);return <><Toolbar><div className="spacer"/><button className="btn primary" onClick={()=>setModal(true)}><Plus size={16}/> Kullanıcı</button></Toolbar><DataTable cols={['Ad Soyad','E-posta','Rol','Kurum','Durum','İlk Şifre']} rows={((q.data as any)?.items||[]).map((x:any)=>[x.full_name,x.email,roleName(x.role),boot.institutions.find(i=>i.id===x.institution_id)?.name||'—',x.status,x.must_change_password?'Değiştirecek':'Tamam'])}/>{modal&&<UserModal boot={boot} close={()=>setModal(false)} saved={()=>{setModal(false);q.reload()}}/>}</>}
function UserModal({boot,close,saved}:{boot:Bootstrap;close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({role:'PERSONEL'});return <Modal title="Kullanıcı oluştur" close={close}><FormGrid><Field label="Ad Soyad"><input value={b.full_name||''} onChange={e=>setB({...b,full_name:e.target.value})}/></Field><Field label="E-posta"><input type="email" value={b.email||''} onChange={e=>setB({...b,email:e.target.value})}/></Field><Field label="Geçici şifre"><input type="password" value={b.password||''} onChange={e=>setB({...b,password:e.target.value})}/></Field><Field label="Rol"><select value={b.role} onChange={e=>setB({...b,role:e.target.value})}><option>ADMIN</option><option>PERSONEL</option><option>OPERASYON</option><option>KURUM</option></select></Field>{b.role==='KURUM'&&<Field label="Kurum"><select value={b.institution_id||''} onChange={e=>setB({...b,institution_id:e.target.value})}><option value="">Seçiniz</option>{boot.institutions.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></Field>}</FormGrid><ModalActions close={close} save={async()=>{await api('/api/users',{method:'POST',body:JSON.stringify(b)});saved()}}/></Modal>}
function Seasons({boot,refreshBoot}:{boot:Bootstrap;refreshBoot:()=>Promise<void>}){const [modal,setModal]=useState(false);return <><div className="card-grid">{boot.seasons.map(s=><div className={`season-card ${s.is_active?'active':''}`} key={s.id}><CalendarRange/><div><h3>{s.name}</h3><p>{s.is_active?'Aktif sezon':'Geçmiş / gelecek sezon'}</p></div></div>)}</div><button className="fab" onClick={()=>setModal(true)}><Plus/></button>{modal&&<SeasonModal close={()=>setModal(false)} saved={async()=>{setModal(false);await refreshBoot()}}/>}</>}
function SeasonModal({close,saved}:{close:()=>void;saved:()=>void}){const [b,setB]=useState<any>({is_active:false});return <Modal title="Sezon ekle" close={close}><FormGrid><Field label="Sezon adı"><input placeholder="2027-2028" value={b.name||''} onChange={e=>setB({...b,name:e.target.value})}/></Field><Field label="Başlangıç yılı"><input type="number" value={b.year_start||''} onChange={e=>setB({...b,year_start:e.target.value})}/></Field><Field label="Bitiş yılı"><input type="number" value={b.year_end||''} onChange={e=>setB({...b,year_end:e.target.value})}/></Field></FormGrid><label className="check"><input type="checkbox" checked={b.is_active} onChange={e=>setB({...b,is_active:e.target.checked})}/> Aktif sezon yap</label><ModalActions close={close} save={async()=>{await api('/api/seasons',{method:'POST',body:JSON.stringify(b)});saved()}}/></Modal>}
function Integration(){const q=useAsync(()=>api('/api/setup/status'),[]);return <div className="grid-2"><Panel title="Cloudflare D1" icon={Warehouse}><div className="integration-status"><CheckCircle2/><div><b>{(q.data as any)?.database?'DB binding bağlı':'DB binding gerekli'}</b><small>{(q.data as any)?.ready?'Veritabanı erişilebilir':'Cloudflare üzerinden D1 bağlantısı tamamlanmalı'}</small></div></div></Panel><Panel title="YILDIZERP" icon={RefreshCw}><div className="integration-status muted-state"><Clock3/><div><b>Hazır, isteğe bağlı</b><small>ERP bağlantısı platform çalışmasını engellemez; daha sonra service binding ile etkinleştirilebilir.</small></div></div></Panel></div>}

function Toolbar({children}:{children:any}){return <div className="toolbar">{children}</div>}
function SearchBox({value,set}:{value:string;set:(x:string)=>void}){return <label className="search"><Search size={16}/><input placeholder="Ara…" value={value} onChange={e=>set(e.target.value)}/></label>}
function DataTable({cols,rows}:{cols:string[];rows:any[][]}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<Empty text="Kayıt bulunamadı."/>}</div>}
function Badge({text,tone='info'}:{text:string;tone?:string}){return <span className={`badge ${tone}`}>{text}</span>}
function Empty({text}:{text:string}){return <div className="empty"><CalendarDays/><p>{text}</p></div>}
function Loading(){return <div className="loading"><RefreshCw className="spin"/> Yükleniyor…</div>}
function ErrorState({text,retry}:{text:string;retry:()=>void}){return <div className="error-state"><AlertTriangle/><b>{text}</b><button className="btn" onClick={retry}>Tekrar dene</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="modal-back" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close}><X/></button></div>{children}</div></div>}
function FormGrid({children}:{children:any}){return <div className="form-grid">{children}</div>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
function ModalActions({close,save}:{close:()=>void;save:()=>void}){const [busy,setBusy]=useState(false),[err,setErr]=useState('');return <><>{err&&<div className="error-box">{err}</div>}</><div className="modal-actions"><button className="btn" onClick={close}>Vazgeç</button><button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);setErr('');try{await save()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}}><Save size={16}/>{busy?'Kaydediliyor…':'Kaydet'}</button></div></>}
